### ISSUE TITLE
Login error validation has two copies of "Please enter a valid email address"

### ISSUE THREAD

**Issue by TeddyHartanto** [nus-mtp/bill-organizer#100]
![image](https://cloud.githubusercontent.com/assets/11240927/24288765/9a2bd728-10b9-11e7-98b1-357d682b9e6e.png)

**Comment by eatedcookie** [comment]
It's different; the first one is if the field is empty, the second one is for if what you entered is not an email address

**Comment by TeddyHartanto** [comment]
Can we delete and make it into 1?  
1. Email not entered -> "Please enter a valid email address"
2. Email entered but invalid -> "Please enter a valid email address"

**Comment by eatedcookie** [comment]
anws i think this is pretty much solved by using inline error msgs?
