### ISSUE TITLE
landing page/dashboard fixes

### ISSUE THREAD

**Issue by eatedcookie** [nus-mtp/bill-organizer#11]
- [x] fix the problem of icon image not loading

**Landing Page**
- [x] automatically redirect to '/dashboard' if user is logged in

**Dashboard**
- [ ] add "upload bill" button
- [x] add clickable placeholder billing organisation that will link to billing organisation page

**Comment by dev-seahouse** [comment]
icon not loading is because of asset/secure asset/url
