### ISSUE TITLE
convert containers to padded segments

### ISSUE THREAD

**Issue by eatedcookie** [nus-mtp/bill-organizer#12]
content containers are currently manually padded to make space for the fixed top menu
switch to using semantic's padded segments for more convenience! (ﾉ^ヮ^)ﾉ*:・ﾟ✧

**Comment by dev-seahouse** [comment]
closed in pull #25, commit https://github.com/nus-mtp/bill-organizer/commit/2cf2fe206f6dc6da57f454c226fda7d990731cbc
