### ISSUE TITLE
configure database

### ISSUE THREAD

**Issue by dev-seahouse** [nus-mtp/bill-organizer#2]
definition of done:
1. a central database is configured and open for connection
2. everyone in the team is able to connect to database via provided db address, username and password
3. database related operations can be performed by laravel using Eloquent with no DB connection exception
4. circle ci is able to access the configured database ( proper settings are configured in circle.yml file)

**Comment by TeddyHartanto** [comment]
DB for production has been set up and proved to work (by registering a user in the heroku website).
As for the development environment, use a local DB.
