### ISSUE TITLE
replace sidebar menu with more suitable component

### ISSUE THREAD

**Issue by eatedcookie** [nus-mtp/bill-organizer#20]
the retractable area that is supposed to display stats

**Comment by dev-seahouse** [comment]
http://jillix.github.io/jQuery-sidebar/   fast and works
https://tympanus.net/Development/SidebarTransitions/ (side on top do the trick,  good:have other fancy effects to draw inspiration. drawback: slow )

**Comment by dev-seahouse** [comment]
this works
<div class="ui button" data-transition="overlay">
        Overlay
 </div>
http://semantic-ui.com/modules/sidebar.html#/examples

**Comment by eatedcookie** [comment]
currently using hidden columns; works fine
