### ISSUE TITLE
database issue when deleting a billing org containing records

### ISSUE THREAD

**Issue by eatedcookie** [nus-mtp/bill-organizer#27]
![del_singtel_issue](https://cloud.githubusercontent.com/assets/13853796/23395485/d7060de2-fdc9-11e6-87c0-49150fda83ad.JPG)

**Comment by dev-seahouse** [comment]
Cause: This happens because records have foreign keys pointing to billing orgs(user_record_issuers), if delete a billing org, records belong to the billorg will have nothing to point to  
solution: set on_delete cascade on user_record_issuer_id foreignt key

**Comment by TeddyHartanto** [comment]
@dev-seahouse yes, i'm aware of that. I will fix that. But we shouldn't be using on delete cascade. I don't want any accidental deletion of a billorg that causes the records to be deleted. We don't want to lose data.

**Comment by TeddyHartanto** [comment]
Fixed in [PR #60](https://github.com/nus-mtp/bill-organizer/pull/60)
