### ISSUE TITLE
display pdf preview when upload a document

### ISSUE THREAD

**Issue by dev-seahouse** [nus-mtp/bill-organizer#30]
- [x] drag and drop file into upload area
- [ ] front end format validation/rejection/message
- [ ] do not upload yet and display pdf preview of file
- [ ] hook up preview area to extract pdf, return selection object
- [ ] send server upload request
- [ ] server store file in session
- [ ] server takes in file, duplicate check, validation -> store pesistence
- [ ] .done(doAjaxUpload()).fail(showFailureMessage()).sucess(otherActions())

**Comment by TeddyHartanto** [comment]
@dev-seahouse are you working on this? If you are, please assign it to yourself.
