### ISSUE TITLE
Heroku R14 Memory Quota Exceeded

### ISSUE THREAD

**Issue by TeddyHartanto** [nus-mtp/bill-organizer#43]
Memory error happens when building commit [4e74d51](https://github.com/nus-mtp/bill-organizer/commit/4e74d51d74d534ad7677611989a2ddc3134daaa0)

![image](https://cloud.githubusercontent.com/assets/11240927/23642602/cf8a6186-0336-11e7-8fb6-7c8e420af126.png)

**Comment by TeddyHartanto** [comment]
Hypothesis: the memory crashed happened when compiling and building assets.

**Comment by eatedcookie** [comment]
@dev-seahouse wad dis???? also why your latest commit to master failed the circleci test?????

**Comment by dev-seahouse** [comment]
https://github.com/JeffreyWay/laravel-mix/issues/478

**Comment by dev-seahouse** [comment]
this happens because one of the vendor dependencies called cross-env.js has changed its build path from bin/ to dist/bin

**Comment by dev-seahouse** [comment]
![image](https://cloud.githubusercontent.com/assets/4751342/23644617/23d650e0-0343-11e7-8dfc-83ba149d085a.png)

**Comment by dev-seahouse** [comment]
![image](https://cloud.githubusercontent.com/assets/4751342/23645023/0ad04ed2-0345-11e7-9e80-f61c5f1226c5.png)

**Comment by dev-seahouse** [comment]
circleci error fixed
reason: when circle ci run npm install, it pull latest package aka updated npm package, so the latest version of cross-env.js changed its buildpath from bin/ to dist/bin  
solution: just need to update package.json to use dist/bin and clear cache
![image](https://cloud.githubusercontent.com/assets/4751342/23645262/3a1929d8-0346-11e7-8569-2442ff7c1f13.png)

**Comment by TeddyHartanto** [comment]
@dev-seahouse this problem is irrelevant of the location of `cross-env.js.` Check the image I posted. It's a memory error. Not an error referencing a file that's not found

**Comment by TeddyHartanto** [comment]
After [PR #44](https://github.com/nus-mtp/bill-organizer/issues/44), the memory crash didn't occur. This doesn't mean that it has been fixed though, will keep this issue open.

**Comment by TeddyHartanto** [comment]
Error still happen occasionally:
![image](https://cloud.githubusercontent.com/assets/11240927/23700299/5d7688a2-042d-11e7-8606-54600d9678a4.png)

Cause confirmed: `npm run production` takes too much memory

Proposed solution:
add to `package.json`'s script part, `heroku-postbuild` script command

**Comment by TeddyHartanto** [comment]
Issue fixed in [PR #47](https://github.com/nus-mtp/bill-organizer/pull/47)
