### ISSUE TITLE
Re: asset folder

### ISSUE THREAD

**Issue by dev-seahouse** [nus-mtp/bill-organizer#69]
public folder is excluded from ci pipeline, however, icons/images are manually placed inside public folder(not compiled)

![image](https://cloud.githubusercontent.com/assets/4751342/23840535/fa98099c-07e0-11e7-860b-ffa31d1482b2.png)

**Comment by TeddyHartanto** [comment]
What's the problem with this? I don't understand. Please elaborate. Anyways, public folder is not ignored. These folders are:
![image](https://cloud.githubusercontent.com/assets/11240927/23840781/f9184d32-07e2-11e7-9d28-ccfe6c9dc50b.png)

**Comment by dev-seahouse** [comment]
public/images is not ignored?
