### ISSUE TITLE
Validate re-entered password match during register

### ISSUE THREAD

**Issue by eatedcookie** [nus-mtp/bill-organizer#76]
apparently semantic's is buggy and tells you that passwords are mismatched no matter what you put

i guess i'll fiddle with it a bit more later before writing my own jquery validation OTL

**Comment by eatedcookie** [comment]
for reference in case i do have to do the jQuery thing:
http://stackoverflow.com/questions/32587177/jquery-validate-compare-two-fields
http://jsfiddle.net/o7vgejsk/
https://jqueryvalidation.org/category/methods/

**Comment by dev-seahouse** [comment]
https://github.com/formvalidation/formvalidation
tried this? validation without clicking submit

**Comment by eatedcookie** [comment]
solved in #75 
issue was that the password field for register was using the same name and id as the password field for login
