### ISSUE TITLE
Heroku assets over http instead of https

### ISSUE THREAD

**Issue by TeddyHartanto** [nus-mtp/bill-organizer#81]
![image](https://cloud.githubusercontent.com/assets/11240927/24026250/b738b45e-0afa-11e7-9bb4-52a67afa8d5b.png)

**Comment by TeddyHartanto** [comment]
@eatedcookie @dev-seahouse I'm gonna fix this. Btw, can we make the assets loading the same across all pages? For instance, the assets loading in app.blade.php and welcome.blade.php is different.

**Comment by dev-seahouse** [comment]
@TeddyHartanto @eatedcookie 
doing this now
[branch: assetLoadingAcrossPage](https://github.com/nus-mtp/bill-organizer/tree/fix/assetLoadingAcrossPage)

**Comment by TeddyHartanto** [comment]
@dev-seahouse Fixed the assets loading, but login and register not working. Anw, I'm moving on to text recognition -- very urgent

**Comment by TeddyHartanto** [comment]
@dev-seahouse eh btw are you coming to the meeting today?

**Comment by TeddyHartanto** [comment]
@dev-seahouse @eatedcookie @chaejinkeyne wanna meet tomorrow? Need to chiong the project

**Comment by dev-seahouse** [comment]
want to come my house tomorrow blow aircon and free food/drink ? i do stuff extremely slow at school
